// <auto-generated />
namespace FarnahadManufacturing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changed_in_paymentTerm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_in_paymentTerm));
        
        string IMigrationMetadata.Id
        {
            get { return "202003081242433_changed_in_paymentTerm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
