// <auto-generated />
namespace FarnahadManufacturing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class added_userGroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_userGroup));
        
        string IMigrationMetadata.Id
        {
            get { return "202002171449337_added_userGroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
