// <auto-generated />
namespace FarnahadManufacturing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changed_address_default_prop_to_bool : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_address_default_prop_to_bool));
        
        string IMigrationMetadata.Id
        {
            get { return "202002191530129_changed_address_default_prop_to_bool"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
