// <auto-generated />
namespace FarnahadManufacturing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changed_uomType_to_enum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_uomType_to_enum));
        
        string IMigrationMetadata.Id
        {
            get { return "202003011749004_changed_uomType_to_enum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
