// <auto-generated />
namespace FarnahadManufacturing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class added_some_props_in_trackingPart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_some_props_in_trackingPart));
        
        string IMigrationMetadata.Id
        {
            get { return "202002281950140_added_some_props_in_trackingPart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
