// <auto-generated />
namespace FarnahadManufacturing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class added_last_change_user_and_date : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_last_change_user_and_date));
        
        string IMigrationMetadata.Id
        {
            get { return "202002281748221_added_last_change_user_and_date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
