// <auto-generated />
namespace FarnahadManufacturing.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class added_productAssociatePrice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_productAssociatePrice));
        
        string IMigrationMetadata.Id
        {
            get { return "202003061441453_added_productAssociatePrice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
